translations = {
    'lang': {
        "uz": "O'zbek 🇺🇿",
        "ru": "Русский 🇷🇺",
        "en": "English 🇺🇸",
    },
    'uz': {
        "benzin": "⛽️Benzin",
        "dizel": "⛽️Dizel",
        "gibrid_be": "⛽️Gibrid (Benzin + Elektr)",
        "gibrid_de": "⛽️Gibrid (Dizel + Elektr)",
        "electr": "⚡️Elektr",
        "choose_type": "Yoqilg'i turini tanlang: ",
        "choose_volume": "Motor hajmini kiriting (cm\u00b3): ",
        "wrong_volume": "Motor hajmini to'g'ri kiriting: ",
        "choose_age": "Mashina yoshini tanlang: ",
        "choose_price": "Mashina narxini kiriting $: ",
        "wrong_price": "Mashina narxini to'g'ri kiriting: ",
        "one_year": "1 yillik",
        "two_plus_year": "2-3 yillik",
        "one_three_year": "1-3 yillik",
        "three_plus_year": "3+ yillik",
        "confirm_data": "Ma'lumotlar to'g'riligini tasdiqlash: ",
        "confirm_type": "🛞Yoqilg'i turi:",
        "confirm_volume": "🚘Mashina motori hajmi:",
        "confirm_age": "⏳Mashina yoshi:",
        "confirm_price": "💵Mashina narxi:",
        "Valyuta narxi:": "Valyuta narxi:",
        "confirm": "✅Tasdiqlash",
        'back': "⬅️Orqaga",
        "cancel": "❌Bekor qilish",
        'home': "🏠Bosh sahifa",
        'price': '💵Mashina narxi: ',
        'type': "🛞Yoqilg'i turi: ",
        "age": "⏳Mashina yoshi: ",
        "usd": "💰AQSH Dollari narxi: ",
        "overall": "Umumiy to'lov: ",
        "fees": "To'lovlar: ",
        "qqs": "QQS (12%): ",
        "boj": "Bojxona boji",
        "yigim": "Bojxona yig'imi",
        "bhm": "BHM",
        "utilization": "Utilizatsiya yig'imi",
        "currency": "so'm"
    },
    'ru': {
        "benzin": "⛽Бензин",
        "dizel": "⛽Дизель",
        "gibrid_be": "⛽Гибрид (Бензин + Электро)",
        "gibrid_de": "⛽Гибрид (Дизель + Электро)",
        "electr": "⚡️Электрический",
        "choose_type": "Выберите тип топлива: ",
        "choose_age": "Выберите возраст автомобиля: ",
        "choose_price": "Введите цену автомобиля в долларах: ",
        "one_year": "1 годовой",
        "two_plus_year": "2-3 года",
        "wrong_price": "Укажите правильную цену автомобиля: ",
        "confirm_type": "🛞Тип топлива:",
        "confirm_data": "Подтвердите правильность данных:",
        "confirm_volume": "🚘Объем двигателя:",
        "confirm_age": "⏳Возраст автомобиля:",
        "confirm_price": "💵Цена автомобиля:",
        "Valyuta narxi:": "Курс валюты:",
        "confirm": "✅Подтвердить",
        'back': "⬅️Назад",
        "cancel": "❌Отменить",
        'home': "🏠Главная",
        "choose_volume": "Введите объем двигателя (cm\u00b3)",
        "wrong_volume": "Введите правильный объем двигателя: ",
        "one_three_year": "1-3 летний",
        "three_plus_year": "3+ летний",
        "price": "💵Цена автомобиля: ",
        "type": "🛞Тип топлива: ",
        "age": "⏳Возраст автомобиля: ",
        "usd": "💰Курс доллара США: ",
        "overall": "Общие импортные платежи: ",
        "fees": "В том числе: ",
        "qqs": "НДС (12%): ",
        "boj": "Таможенная пошлина",
        "yigim": "Таможенный сбор",
        "bhm": "БРВ",
        "utilization": "Утилизационный сбор",
        "currency": "cум"
    },
    'en': {
        "benzin": "⛽Petrol",
        "dizel": "⛽Diesel",
        "gibrid_be": "⛽Hybrid (Petrol + Electric)",
        "gibrid_de": "⛽Hybrid (Diesel + Electric)",
        "electr": "⚡️Electric",
        "choose_type": "Choose the fuel type: ",
        "choose_age": "Choose the car age: ",
        "choose_price": "Enter the car price in $: ",
        "one_year": "1 year old",
        "two_plus_year": "2-3 years old",
        "wrong_price": "Enter the price correctly: ",
        "confirm_data": "Confirm the data: ",
        "confirm_type": "🛞Fuel type:",
        "confirm_volume": "🚘Engine capacity:",
        "confirm_age": "⏳Car age:",
        "confirm_price": "💵Car price:",
        "Valyuta narxi:": "Exchange rate:",
        "confirm": "✅Confirm",
        'back': "⬅️Back",
        "cancel": "❌Cancel",
        'home': "🏠Home",
        "choose_volume": "Enter the engine capacity (cm\u00b3): ",
        "wrong_volume": "Enter the engine capacity correctly: ",
        "one_three_year": "1-3 years old",
        "three_plus_year": "3+ years old",
        "price": "💵Car price: ",
        "type": "🛞Fuel type: ",
        "age": "⏳Car age: ",
        "usd": "💰US Dollar exchange rate: ",
        "overall": "Total import duties: ",
        "fees": "Including: ",
        "qqs": "VAT (12%): ",
        "boj": "Customs duty",
        "yigim": "Customs fee",
        "bhm": "BCA",
        "utilization": "Utilization fee",
        "currency": "soums"
    }
}
